server:
  port: 8082
spring:
  application:
    name: Item_cards
  datasource:
    url: jdbc:h2:file:./demodb
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
headers:
  X-API-Key: jsHz5gKqU3VXerXJ1zGLABmd
file:
  resource-dir: src/main/resources/static/photo_without_background
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

